(function(global){
  const DATA = {
    1: {
      atomic_mass: "1.008",
      phase: "Gas",
      appearance: "Gas incolore e inodore",
      electron_configuration: "1s1",
      electronegativity_pauling: "2.20",
      atomic_radius: "53",
      covalent_radius_pm: "31",
      ionization_energy_kjmol: "1312",
      oxidation_states: "-1, +1",
      density_gcm3: "0.0000899",
      melt: "13.99",
      boil: "20.271",
      discovered_by: "Henry Cavendish",
      discovery_year: "1766",
      uses: "Carburante per razzi, celle a combustibile e produzione di ammoniaca."
    },
    2: {
      atomic_mass: "4.002602",
      phase: "Gas",
      appearance: "Gas nobile incolore",
      electron_configuration: "1s2",
      electronegativity_pauling: "—",
      atomic_radius: "31",
      covalent_radius_pm: "28",
      ionization_energy_kjmol: "2372",
      oxidation_states: "0",
      density_gcm3: "0.0001785",
      melt: "0.95",
      boil: "4.222",
      discovered_by: "Pierre Janssen e Joseph Norman Lockyer",
      discovery_year: "1868",
      uses: "Gas di riempimento per palloni, criogenia e miscele respiratorie profonde."
    },
    3: {
      atomic_mass: "6.94",
      phase: "Solido",
      appearance: "Metallo argenteo morbido",
      electron_configuration: "[He] 2s1",
      electronegativity_pauling: "0.98",
      atomic_radius: "167",
      covalent_radius_pm: "128",
      ionization_energy_kjmol: "520",
      oxidation_states: "+1",
      density_gcm3: "0.534",
      melt: "453.69",
      boil: "1603",
      discovered_by: "Johan August Arfwedson",
      discovery_year: "1817",
      uses: "Batterie ricaricabili, leghe leggere e medicinali per disturbi bipolari."
    },
    4: {
      atomic_mass: "9.0121831",
      phase: "Solido",
      appearance: "Metallo grigio acciaio",
      electron_configuration: "[He] 2s2",
      electronegativity_pauling: "1.57",
      atomic_radius: "112",
      covalent_radius_pm: "96",
      ionization_energy_kjmol: "900",
      oxidation_states: "+2",
      density_gcm3: "1.85",
      melt: "1560",
      boil: "2742",
      discovered_by: "Louis Nicolas Vauquelin",
      discovery_year: "1798",
      uses: "Finestre per raggi X, leghe leggere e materiali per reattori nucleari."
    },
    5: {
      atomic_mass: "10.81",
      phase: "Solido",
      appearance: "Solido nero o marrone",
      electron_configuration: "[He] 2s2 2p1",
      electronegativity_pauling: "2.04",
      atomic_radius: "87",
      covalent_radius_pm: "85",
      ionization_energy_kjmol: "801",
      oxidation_states: "+3",
      density_gcm3: "2.34",
      melt: "2349",
      boil: "4200",
      discovered_by: "Joseph-Louis Gay-Lussac e Louis Jacques Thénard",
      discovery_year: "1808",
      uses: "Vetri borosilicati, detergenti, magneti NdFeB e semiconduttori."
    },
    6: {
      atomic_mass: "12.011",
      phase: "Solido",
      appearance: "Solido in varie forme allotropiche",
      electron_configuration: "[He] 2s2 2p2",
      electronegativity_pauling: "2.55",
      atomic_radius: "67",
      covalent_radius_pm: "76",
      ionization_energy_kjmol: "1086",
      oxidation_states: "-4, +2, +4",
      density_gcm3: "2.267",
      melt: "3823",
      boil: "4098",
      discovered_by: "Preistoria",
      discovery_year: "—",
      uses: "Base della chimica organica, materiali compositi, filtri e combustibili."
    },
    7: {
      atomic_mass: "14.007",
      phase: "Gas",
      appearance: "Gas incolore",
      electron_configuration: "[He] 2s2 2p3",
      electronegativity_pauling: "3.04",
      atomic_radius: "56",
      covalent_radius_pm: "71",
      ionization_energy_kjmol: "1402",
      oxidation_states: "-3, +3, +5",
      density_gcm3: "0.0012506",
      melt: "63.15",
      boil: "77.36",
      discovered_by: "Daniel Rutherford",
      discovery_year: "1772",
      uses: "Fertilizzanti, esplosivi, atmosfere inerti e industria elettronica."
    },
    8: {
      atomic_mass: "15.999",
      phase: "Gas",
      appearance: "Gas incolore",
      electron_configuration: "[He] 2s2 2p4",
      electronegativity_pauling: "3.44",
      atomic_radius: "48",
      covalent_radius_pm: "66",
      ionization_energy_kjmol: "1314",
      oxidation_states: "-2",
      density_gcm3: "0.001429",
      melt: "54.36",
      boil: "90.20",
      discovered_by: "Carl Wilhelm Scheele",
      discovery_year: "1774",
      uses: "Respirazione, combustione, trattamento delle acque e produzione di acciaio."
    },
    9: {
      atomic_mass: "18.998403163",
      phase: "Gas",
      appearance: "Gas giallo-verde pallido",
      electron_configuration: "[He] 2s2 2p5",
      electronegativity_pauling: "3.98",
      atomic_radius: "42",
      covalent_radius_pm: "57",
      ionization_energy_kjmol: "1681",
      oxidation_states: "-1",
      density_gcm3: "0.001696",
      melt: "53.48",
      boil: "85.03",
      discovered_by: "Henri Moissan",
      discovery_year: "1886",
      uses: "Fluoruri per refrigeranti, UF6 per arricchimento e produzione di Teflon."
    },
    10: {
      atomic_mass: "20.1797",
      phase: "Gas",
      appearance: "Gas incolore",
      electron_configuration: "[He] 2s2 2p6",
      electronegativity_pauling: "—",
      atomic_radius: "38",
      covalent_radius_pm: "58",
      ionization_energy_kjmol: "2080",
      oxidation_states: "0",
      density_gcm3: "0.0008999",
      melt: "24.56",
      boil: "27.07",
      discovered_by: "Morris Travers e William Ramsay",
      discovery_year: "1898",
      uses: "Insegne luminose, criogenia e laser a neon."
    },
    11: {
      atomic_mass: "22.98976928",
      phase: "Solido",
      appearance: "Metallo argenteo morbido",
      electron_configuration: "[Ne] 3s1",
      electronegativity_pauling: "0.93",
      atomic_radius: "190",
      covalent_radius_pm: "166",
      ionization_energy_kjmol: "496",
      oxidation_states: "+1",
      density_gcm3: "0.971",
      melt: "370.87",
      boil: "1156",
      discovered_by: "Humphry Davy",
      discovery_year: "1807",
      uses: "Lampade al sodio, scambio ionico, sale da cucina e vetro."
    },
    12: {
      atomic_mass: "24.305",
      phase: "Solido",
      appearance: "Metallo grigio lucente",
      electron_configuration: "[Ne] 3s2",
      electronegativity_pauling: "1.31",
      atomic_radius: "145",
      covalent_radius_pm: "141",
      ionization_energy_kjmol: "738",
      oxidation_states: "+2",
      density_gcm3: "1.738",
      melt: "923",
      boil: "1363",
      discovered_by: "Joseph Black",
      discovery_year: "1755",
      uses: "Leghe leggere, strutture aeronautiche e antacidi."
    },
    13: {
      atomic_mass: "26.9815385",
      phase: "Solido",
      appearance: "Metallo argenteo",
      electron_configuration: "[Ne] 3s2 3p1",
      electronegativity_pauling: "1.61",
      atomic_radius: "118",
      covalent_radius_pm: "121",
      ionization_energy_kjmol: "578",
      oxidation_states: "+3",
      density_gcm3: "2.70",
      melt: "933.47",
      boil: "2792",
      discovered_by: "Hans Christian Ørsted",
      discovery_year: "1825",
      uses: "Imballaggi, costruzioni leggere, cavi elettrici e leghe."
    },
    14: {
      atomic_mass: "28.085",
      phase: "Solido",
      appearance: "Metalloide grigio scuro",
      electron_configuration: "[Ne] 3s2 3p2",
      electronegativity_pauling: "1.90",
      atomic_radius: "111",
      covalent_radius_pm: "111",
      ionization_energy_kjmol: "786",
      oxidation_states: "-4, +2, +4",
      density_gcm3: "2.3296",
      melt: "1687",
      boil: "3538",
      discovered_by: "Jöns Jacob Berzelius",
      discovery_year: "1824",
      uses: "Circuiti integrati, pannelli solari e vetri speciali."
    },
    15: {
      atomic_mass: "30.973761998",
      phase: "Solido",
      appearance: "Solido bianco/rosso/nero (allotropi)",
      electron_configuration: "[Ne] 3s2 3p3",
      electronegativity_pauling: "2.19",
      atomic_radius: "98",
      covalent_radius_pm: "107",
      ionization_energy_kjmol: "1012",
      oxidation_states: "-3, +3, +5",
      density_gcm3: "1.82",
      melt: "317.30",
      boil: "553",
      discovered_by: "Hennig Brand",
      discovery_year: "1669",
      uses: "Fertilizzanti, fiammiferi, detergenti e processi metallurgici."
    },
    16: {
      atomic_mass: "32.06",
      phase: "Solido",
      appearance: "Solido giallo (forma ortorombica)",
      electron_configuration: "[Ne] 3s2 3p4",
      electronegativity_pauling: "2.58",
      atomic_radius: "88",
      covalent_radius_pm: "105",
      ionization_energy_kjmol: "999",
      oxidation_states: "-2, +2, +4, +6",
      density_gcm3: "2.07",
      melt: "388.36",
      boil: "717.8",
      discovered_by: "Preistoria",
      discovery_year: "—",
      uses: "Vulcanizzazione della gomma, fertilizzanti e prodotti farmaceutici."
    },
    17: {
      atomic_mass: "35.45",
      phase: "Gas",
      appearance: "Gas giallo-verde",
      electron_configuration: "[Ne] 3s2 3p5",
      electronegativity_pauling: "3.16",
      atomic_radius: "79",
      covalent_radius_pm: "102",
      ionization_energy_kjmol: "1251",
      oxidation_states: "-1, +1, +3, +5, +7",
      density_gcm3: "0.003214",
      melt: "171.6",
      boil: "239.11",
      discovered_by: "Carl Wilhelm Scheele",
      discovery_year: "1774",
      uses: "Disinfettanti, sale, PVC e sbiancamento della carta."
    },
    18: {
      atomic_mass: "39.948",
      phase: "Gas",
      appearance: "Gas nobile incolore",
      electron_configuration: "[Ne] 3s2 3p6",
      electronegativity_pauling: "—",
      atomic_radius: "71",
      covalent_radius_pm: "106",
      ionization_energy_kjmol: "1521",
      oxidation_states: "0",
      density_gcm3: "0.001784",
      melt: "83.81",
      boil: "87.30",
      discovered_by: "Lord Rayleigh e William Ramsay",
      discovery_year: "1894",
      uses: "Illuminazione, laser, atmosfere inerti e anestesia."
    },
    19: {
      atomic_mass: "39.0983",
      phase: "Solido",
      appearance: "Metallo argenteo",
      electron_configuration: "[Ar] 4s1",
      electronegativity_pauling: "0.82",
      atomic_radius: "243",
      covalent_radius_pm: "203",
      ionization_energy_kjmol: "419",
      oxidation_states: "+1",
      density_gcm3: "0.862",
      melt: "336.53",
      boil: "1032",
      discovered_by: "Martin Heinrich Klaproth",
      discovery_year: "1807",
      uses: "Fertilizzanti, saponi, sali potassici e pirotecnica."
    },
    20: {
      atomic_mass: "40.078",
      phase: "Solido",
      appearance: "Metallo argenteo",
      electron_configuration: "[Ar] 4s2",
      electronegativity_pauling: "1.00",
      atomic_radius: "194",
      covalent_radius_pm: "176",
      ionization_energy_kjmol: "590",
      oxidation_states: "+2",
      density_gcm3: "1.55",
      melt: "1115",
      boil: "1757",
      discovered_by: "Humphry Davy",
      discovery_year: "1808",
      uses: "Calce, cemento, integratori alimentari e pirotecnica."
    },
    21: {
      atomic_mass: "44.955908",
      phase: "Solido",
      appearance: "Metallo grigio",
      electron_configuration: "[Ar] 3d1 4s2",
      electronegativity_pauling: "1.36",
      atomic_radius: "184",
      covalent_radius_pm: "170",
      ionization_energy_kjmol: "633",
      oxidation_states: "+3",
      density_gcm3: "2.989",
      melt: "1814",
      boil: "3109",
      discovered_by: "Lars Fredrik Nilson",
      discovery_year: "1879",
      uses: "Leghe leggere, impianti aerospaziali e componenti elettronici."
    },
    22: {
      atomic_mass: "47.867",
      phase: "Solido",
      appearance: "Metallo lucente",
      electron_configuration: "[Ar] 3d2 4s2",
      electronegativity_pauling: "1.54",
      atomic_radius: "176",
      covalent_radius_pm: "160",
      ionization_energy_kjmol: "658",
      oxidation_states: "+2, +3, +4",
      density_gcm3: "4.506",
      melt: "1941",
      boil: "3560",
      discovered_by: "William Gregor",
      discovery_year: "1791",
      uses: "Leghe aeronautiche, pigmenti e impianti medici."
    },
    23: {
      atomic_mass: "50.9415",
      phase: "Solido",
      appearance: "Metallo grigio-argenteo",
      electron_configuration: "[Ar] 3d3 4s2",
      electronegativity_pauling: "1.63",
      atomic_radius: "171",
      covalent_radius_pm: "153",
      ionization_energy_kjmol: "651",
      oxidation_states: "+2, +3, +4, +5",
      density_gcm3: "6.0",
      melt: "2183",
      boil: "3680",
      discovered_by: "Andrés Manuel del Río",
      discovery_year: "1801",
      uses: "Leghe speciali, catalizzatori e batterie a flusso."
    },
    24: {
      atomic_mass: "51.9961",
      phase: "Solido",
      appearance: "Metallo lucente grigio",
      electron_configuration: "[Ar] 3d5 4s1",
      electronegativity_pauling: "1.66",
      atomic_radius: "166",
      covalent_radius_pm: "139",
      ionization_energy_kjmol: "653",
      oxidation_states: "+2, +3, +6",
      density_gcm3: "7.19",
      melt: "2180",
      boil: "2944",
      discovered_by: "Louis Nicolas Vauquelin",
      discovery_year: "1797",
      uses: "Acciai inossidabili, cromature e catalizzatori."
    },
    25: {
      atomic_mass: "54.938044",
      phase: "Solido",
      appearance: "Metallo grigio-argenteo",
      electron_configuration: "[Ar] 3d5 4s2",
      electronegativity_pauling: "1.55",
      atomic_radius: "161",
      covalent_radius_pm: "139",
      ionization_energy_kjmol: "717",
      oxidation_states: "+2, +3, +4, +6, +7",
      density_gcm3: "7.21",
      melt: "1519",
      boil: "2334",
      discovered_by: "Johan Gottlieb Gahn",
      discovery_year: "1774",
      uses: "Leghe, batterie alcaline e catalisi industriale."
    },
    26: {
      atomic_mass: "55.845",
      phase: "Solido",
      appearance: "Metallo grigio lucente",
      electron_configuration: "[Ar] 3d6 4s2",
      electronegativity_pauling: "1.83",
      atomic_radius: "156",
      covalent_radius_pm: "132",
      ionization_energy_kjmol: "762",
      oxidation_states: "+2, +3",
      density_gcm3: "7.874",
      melt: "1811",
      boil: "3134",
      discovered_by: "Preistoria",
      discovery_year: "—",
      uses: "Acciaio, edilizia, trasporti e catalizzatori."
    },
    27: {
      atomic_mass: "58.933194",
      phase: "Solido",
      appearance: "Metallo blu-grigio",
      electron_configuration: "[Ar] 3d7 4s2",
      electronegativity_pauling: "1.88",
      atomic_radius: "152",
      covalent_radius_pm: "126",
      ionization_energy_kjmol: "760",
      oxidation_states: "+2, +3",
      density_gcm3: "8.90",
      melt: "1768",
      boil: "3200",
      discovered_by: "Georg Brandt",
      discovery_year: "1735",
      uses: "Superleghe, catalizzatori e pigmenti blu."
    },
    28: {
      atomic_mass: "58.6934",
      phase: "Solido",
      appearance: "Metallo argenteo",
      electron_configuration: "[Ar] 3d8 4s2",
      electronegativity_pauling: "1.91",
      atomic_radius: "149",
      covalent_radius_pm: "124",
      ionization_energy_kjmol: "737",
      oxidation_states: "-1, +2, +3, +4",
      density_gcm3: "8.908",
      melt: "1728",
      boil: "3005",
      discovered_by: "Axel Fredrik Cronstedt",
      discovery_year: "1751",
      uses: "Leghe resistenti alla corrosione, catalizzatori e batterie."
    },
    29: {
      atomic_mass: "63.546",
      phase: "Solido",
      appearance: "Metallo rossiccio",
      electron_configuration: "[Ar] 3d10 4s1",
      electronegativity_pauling: "1.90",
      atomic_radius: "145",
      covalent_radius_pm: "132",
      ionization_energy_kjmol: "745",
      oxidation_states: "+1, +2",
      density_gcm3: "8.96",
      melt: "1357.77",
      boil: "2835",
      discovered_by: "Preistoria",
      discovery_year: "—",
      uses: "Conduttori elettrici, leghe, architettura e antimicrobico."
    },
    30: {
      atomic_mass: "65.38",
      phase: "Solido",
      appearance: "Metallo blu-bianco",
      electron_configuration: "[Ar] 3d10 4s2",
      electronegativity_pauling: "1.65",
      atomic_radius: "142",
      covalent_radius_pm: "122",
      ionization_energy_kjmol: "906",
      oxidation_states: "+2",
      density_gcm3: "7.14",
      melt: "692.68",
      boil: "1180",
      discovered_by: "Andreas Marggraf",
      discovery_year: "1746",
      uses: "Galvanizzazione, leghe a bassa fusione e batterie."
    },
    31: {
      atomic_mass: "69.723",
      phase: "Solido",
      appearance: "Metallo blu-grigio",
      electron_configuration: "[Ar] 3d10 4s2 4p1",
      electronegativity_pauling: "1.81",
      atomic_radius: "136",
      covalent_radius_pm: "122",
      ionization_energy_kjmol: "579",
      oxidation_states: "+3",
      density_gcm3: "5.91",
      melt: "302.91",
      boil: "2477",
      discovered_by: "Paul-Émile Lecoq de Boisbaudran",
      discovery_year: "1875",
      uses: "LED, semiconduttori e leghe a bassa fusione."
    },
    32: {
      atomic_mass: "72.630",
      phase: "Solido",
      appearance: "Metalloide grigio lucente",
      electron_configuration: "[Ar] 3d10 4s2 4p2",
      electronegativity_pauling: "2.01",
      atomic_radius: "125",
      covalent_radius_pm: "120",
      ionization_energy_kjmol: "762",
      oxidation_states: "-4, +2, +4",
      density_gcm3: "5.32",
      melt: "1211.4",
      boil: "3106",
      discovered_by: "Clemens Winkler",
      discovery_year: "1886",
      uses: "Fibre ottiche, semiconduttori e leghe."
    },
    33: {
      atomic_mass: "74.921595",
      phase: "Solido",
      appearance: "Metalloide grigio metallizzato",
      electron_configuration: "[Ar] 3d10 4s2 4p3",
      electronegativity_pauling: "2.18",
      atomic_radius: "114",
      covalent_radius_pm: "119",
      ionization_energy_kjmol: "947",
      oxidation_states: "-3, +3, +5",
      density_gcm3: "5.73",
      melt: "1090",
      boil: "876",
      discovered_by: "Albertus Magnus",
      discovery_year: "1250",
      uses: "Leghe, semiconduttori, pesticidi e vetri speciali."
    },
    34: {
      atomic_mass: "78.971",
      phase: "Solido",
      appearance: "Solido grigio metallizzato",
      electron_configuration: "[Ar] 3d10 4s2 4p4",
      electronegativity_pauling: "2.55",
      atomic_radius: "103",
      covalent_radius_pm: "120",
      ionization_energy_kjmol: "941",
      oxidation_states: "-2, +2, +4, +6",
      density_gcm3: "4.81",
      melt: "494",
      boil: "958",
      discovered_by: "Jöns Jacob Berzelius",
      discovery_year: "1817",
      uses: "Elettronica, vetri, lubrificanti solidi e additivi alimentari."
    },
    35: {
      atomic_mass: "79.904",
      phase: "Liquido",
      appearance: "Liquido rosso-bruno",
      electron_configuration: "[Ar] 3d10 4s2 4p5",
      electronegativity_pauling: "2.96",
      atomic_radius: "94",
      covalent_radius_pm: "120",
      ionization_energy_kjmol: "1140",
      oxidation_states: "-1, +1, +3, +5",
      density_gcm3: "3.12",
      melt: "265.8",
      boil: "332",
      discovered_by: "Antoine Balard",
      discovery_year: "1826",
      uses: "Fotografia, disinfettanti e ritardanti di fiamma."
    },
    36: {
      atomic_mass: "83.798",
      phase: "Gas",
      appearance: "Gas incolore",
      electron_configuration: "[Ar] 3d10 4s2 4p6",
      electronegativity_pauling: "—",
      atomic_radius: "88",
      covalent_radius_pm: "116",
      ionization_energy_kjmol: "1351",
      oxidation_states: "0",
      density_gcm3: "0.003733",
      melt: "115.78",
      boil: "119.93",
      discovered_by: "William Ramsay e Morris Travers",
      discovery_year: "1898",
      uses: "Illuminazione, flash fotografici e rivelatori di radiazioni."
    },
    37: {
      atomic_mass: "85.4678",
      phase: "Solido",
      appearance: "Metallo grigio argenteo",
      electron_configuration: "[Kr] 5s1",
      electronegativity_pauling: "0.82",
      atomic_radius: "265",
      covalent_radius_pm: "216",
      ionization_energy_kjmol: "403",
      oxidation_states: "+1",
      density_gcm3: "1.532",
      melt: "312.46",
      boil: "961",
      discovered_by: "Robert Bunsen e Gustav Kirchhoff",
      discovery_year: "1861",
      uses: "Orologi atomici, cellule fotoelettriche e ricerca."
    },
    38: {
      atomic_mass: "87.62",
      phase: "Solido",
      appearance: "Metallo argenteo",
      electron_configuration: "[Kr] 5s2",
      electronegativity_pauling: "0.95",
      atomic_radius: "219",
      covalent_radius_pm: "191",
      ionization_energy_kjmol: "550",
      oxidation_states: "+2",
      density_gcm3: "2.64",
      melt: "1050",
      boil: "1655",
      discovered_by: "Humphry Davy",
      discovery_year: "1808",
      uses: "Fuochi d'artificio, luminescenza e leghe per magneti."
    },
    39: {
      atomic_mass: "88.90584",
      phase: "Solido",
      appearance: "Metallo grigio scuro",
      electron_configuration: "[Kr] 4d1 5s2",
      electronegativity_pauling: "1.22",
      atomic_radius: "212",
      covalent_radius_pm: "180",
      ionization_energy_kjmol: "600",
      oxidation_states: "+3",
      density_gcm3: "4.47",
      melt: "1799",
      boil: "3618",
      discovered_by: "Johan Gadolin",
      discovery_year: "1794",
      uses: "Laser YAG, superconduttori e leghe ad alte prestazioni."
    },
    40: {
      atomic_mass: "91.224",
      phase: "Solido",
      appearance: "Metallo grigio",
      electron_configuration: "[Kr] 4d2 5s2",
      electronegativity_pauling: "1.33",
      atomic_radius: "206",
      covalent_radius_pm: "175",
      ionization_energy_kjmol: "640",
      oxidation_states: "+4",
      density_gcm3: "6.52",
      melt: "2128",
      boil: "4682",
      discovered_by: "Martin Heinrich Klaproth",
      discovery_year: "1789",
      uses: "Rivestimenti resistenti, barre nucleari e ceramiche avanzate."
    },
    41: {
      atomic_mass: "92.90637",
      phase: "Solido",
      appearance: "Metallo grigio lucente",
      electron_configuration: "[Kr] 4d4 5s1",
      electronegativity_pauling: "1.6",
      atomic_radius: "198",
      covalent_radius_pm: "164",
      ionization_energy_kjmol: "652",
      oxidation_states: "+3, +5",
      density_gcm3: "8.57",
      melt: "2750",
      boil: "5017",
      discovered_by: "Charles Hatchett",
      discovery_year: "1801",
      uses: "Superleghe, acciai speciali e condensatori."
    },
    42: {
      atomic_mass: "95.95",
      phase: "Solido",
      appearance: "Metallo grigio",
      electron_configuration: "[Kr] 4d5 5s1",
      electronegativity_pauling: "2.16",
      atomic_radius: "190",
      covalent_radius_pm: "154",
      ionization_energy_kjmol: "684",
      oxidation_states: "+4, +6",
      density_gcm3: "10.28",
      melt: "2896",
      boil: "4912",
      discovered_by: "Carl Wilhelm Scheele",
      discovery_year: "1778",
      uses: "Acciai temprati, catalizzatori e lubrificanti resistenti al calore."
    },
    43: {
      atomic_mass: "98",
      phase: "Solido",
      appearance: "Metallo grigio",
      electron_configuration: "[Kr] 4d5 5s2",
      electronegativity_pauling: "1.9",
      atomic_radius: "183",
      covalent_radius_pm: "147",
      ionization_energy_kjmol: "702",
      oxidation_states: "+4, +6, +7",
      density_gcm3: "11",
      melt: "2430",
      boil: "4538",
      discovered_by: "Carlo Perrier e Emilio Segrè",
      discovery_year: "1937",
      uses: "Sorgenti radioattive per diagnostica e ricerca."
    },
    44: {
      atomic_mass: "101.07",
      phase: "Solido",
      appearance: "Metallo argenteo",
      electron_configuration: "[Kr] 4d7 5s1",
      electronegativity_pauling: "2.2",
      atomic_radius: "178",
      covalent_radius_pm: "142",
      ionization_energy_kjmol: "710",
      oxidation_states: "+2, +3, +4, +6, +8",
      density_gcm3: "12.37",
      melt: "2607",
      boil: "4423",
      discovered_by: "Karl Karlovich Klaus",
      discovery_year: "1844",
      uses: "Catalizzatori, contatti elettrici e rivestimenti resistenti."
    },
    45: {
      atomic_mass: "102.90549",
      phase: "Solido",
      appearance: "Metallo bianco-argenteo",
      electron_configuration: "[Kr] 4d8 5s1",
      electronegativity_pauling: "2.28",
      atomic_radius: "173",
      covalent_radius_pm: "138",
      ionization_energy_kjmol: "719",
      oxidation_states: "+1, +2, +3, +4, +6",
      density_gcm3: "12.41",
      melt: "2237",
      boil: "3968",
      discovered_by: "William Hyde Wollaston",
      discovery_year: "1803",
      uses: "Catalizzatori, gioielleria e rivestimenti per contatti elettrici."
    },
    46: {
      atomic_mass: "106.42",
      phase: "Solido",
      appearance: "Metallo bianco brillante",
      electron_configuration: "[Kr] 4d10",
      electronegativity_pauling: "2.20",
      atomic_radius: "169",
      covalent_radius_pm: "139",
      ionization_energy_kjmol: "804",
      oxidation_states: "0, +2, +4",
      density_gcm3: "12.02",
      melt: "1828.05",
      boil: "3236",
      discovered_by: "William Hyde Wollaston",
      discovery_year: "1803",
      uses: "Convertitori catalitici, gioielli e contatti elettrici."
    },
    47: {
      atomic_mass: "107.8682",
      phase: "Solido",
      appearance: "Metallo bianco lucente",
      electron_configuration: "[Kr] 4d10 5s1",
      electronegativity_pauling: "1.93",
      atomic_radius: "165",
      covalent_radius_pm: "144",
      ionization_energy_kjmol: "731",
      oxidation_states: "+1, +2",
      density_gcm3: "10.49",
      melt: "1234.93",
      boil: "2435",
      discovered_by: "Preistoria",
      discovery_year: "—",
      uses: "Gioielli, fotografia, elettronica e catalisi."
    },
    48: {
      atomic_mass: "112.414",
      phase: "Solido",
      appearance: "Metallo bianco-argenteo",
      electron_configuration: "[Kr] 4d10 5s2",
      electronegativity_pauling: "1.69",
      atomic_radius: "161",
      covalent_radius_pm: "144",
      ionization_energy_kjmol: "868",
      oxidation_states: "+2",
      density_gcm3: "8.65",
      melt: "594.22",
      boil: "1040",
      discovered_by: "Karl Samuel Leberecht Hermann e Friedrich Stromeyer",
      discovery_year: "1817",
      uses: "Batterie NiCd, schermature neutroniche e pigmenti."
    },
    49: {
      atomic_mass: "114.818",
      phase: "Solido",
      appearance: "Metallo lucente grigio",
      electron_configuration: "[Kr] 4d10 5s2 5p1",
      electronegativity_pauling: "1.78",
      atomic_radius: "156",
      covalent_radius_pm: "142",
      ionization_energy_kjmol: "558",
      oxidation_states: "+1, +3",
      density_gcm3: "7.31",
      melt: "429.75",
      boil: "2345",
      discovered_by: "Ferdinand Reich e Hieronymous Richter",
      discovery_year: "1863",
      uses: "Display LCD, leghe e rivestimenti anticorrosione."
    },
    50: {
      atomic_mass: "118.710",
      phase: "Solido",
      appearance: "Metallo bianco-argenteo",
      electron_configuration: "[Kr] 4d10 5s2 5p2",
      electronegativity_pauling: "1.96",
      atomic_radius: "145",
      covalent_radius_pm: "139",
      ionization_energy_kjmol: "709",
      oxidation_states: "+2, +4",
      density_gcm3: "7.29",
      melt: "505.08",
      boil: "2875",
      discovered_by: "Preistoria",
      discovery_year: "—",
      uses: "Stagno, leghe saldanti e rivestimenti protettivi."
    },
    51: {
      atomic_mass: "121.760",
      phase: "Solido",
      appearance: "Metalloide grigio lucente",
      electron_configuration: "[Kr] 4d10 5s2 5p3",
      electronegativity_pauling: "2.05",
      atomic_radius: "133",
      covalent_radius_pm: "139",
      ionization_energy_kjmol: "834",
      oxidation_states: "-3, +3, +5",
      density_gcm3: "6.697",
      melt: "904",
      boil: "1860",
      discovered_by: "Preistoria",
      discovery_year: "—",
      uses: "Rivestimenti antifrizione, leghe, semiconduttori e fiammiferi."
    },
    52: {
      atomic_mass: "127.60",
      phase: "Solido",
      appearance: "Metalloide grigio argenteo",
      electron_configuration: "[Kr] 4d10 5s2 5p4",
      electronegativity_pauling: "2.10",
      atomic_radius: "123",
      covalent_radius_pm: "138",
      ionization_energy_kjmol: "869",
      oxidation_states: "-2, +2, +4, +6",
      density_gcm3: "6.24",
      melt: "722.66",
      boil: "1261",
      discovered_by: "Franz-Joseph Müller von Reichenstein",
      discovery_year: "1782",
      uses: "Termoelettrici, leghe e additivi per la gomma."
    },
    53: {
      atomic_mass: "126.90447",
      phase: "Solido",
      appearance: "Solido violaceo lucente",
      electron_configuration: "[Kr] 4d10 5s2 5p5",
      electronegativity_pauling: "2.66",
      atomic_radius: "115",
      covalent_radius_pm: "139",
      ionization_energy_kjmol: "1008",
      oxidation_states: "-1, +1, +3, +5, +7",
      density_gcm3: "4.93",
      melt: "386.85",
      boil: "457.4",
      discovered_by: "Bernard Courtois",
      discovery_year: "1811",
      uses: "Antisettici, sali iodati, coloranti e catalizzatori."
    },
    54: {
      atomic_mass: "131.293",
      phase: "Gas",
      appearance: "Gas nobile incolore",
      electron_configuration: "[Kr] 4d10 5s2 5p6",
      electronegativity_pauling: "—",
      atomic_radius: "108",
      covalent_radius_pm: "140",
      ionization_energy_kjmol: "1170",
      oxidation_states: "0",
      density_gcm3: "0.005887",
      melt: "161.4",
      boil: "165.1",
      discovered_by: "William Ramsay e Morris Travers",
      discovery_year: "1898",
      uses: "Luci stroboscopiche, anestesia e rivelatori di radiazioni."
    },
    55: {
      atomic_mass: "132.90545196",
      phase: "Solido",
      appearance: "Metallo argenteo dorato",
      electron_configuration: "[Xe] 6s1",
      electronegativity_pauling: "0.79",
      atomic_radius: "298",
      covalent_radius_pm: "225",
      ionization_energy_kjmol: "376",
      oxidation_states: "+1",
      density_gcm3: "1.93",
      melt: "301.59",
      boil: "944",
      discovered_by: "Andreas Marggraf",
      discovery_year: "1860",
      uses: "Orologi atomici, fotocellule e catalisi organica."
    },
    56: {
      atomic_mass: "137.327",
      phase: "Solido",
      appearance: "Metallo argenteo",
      electron_configuration: "[Xe] 6s2",
      electronegativity_pauling: "0.89",
      atomic_radius: "253",
      covalent_radius_pm: "215",
      ionization_energy_kjmol: "503",
      oxidation_states: "+2",
      density_gcm3: "3.62",
      melt: "1000",
      boil: "2170",
      discovered_by: "Carl Wilhelm Scheele",
      discovery_year: "1772",
      uses: "Lanterne, vetri speciali e medicina diagnostica."
    },
    57: {
      atomic_mass: "138.90547",
      phase: "Solido",
      appearance: "Metallo argenteo",
      electron_configuration: "[Xe] 5d1 6s2",
      electronegativity_pauling: "1.10",
      atomic_radius: "240",
      covalent_radius_pm: "195",
      ionization_energy_kjmol: "538",
      oxidation_states: "+3",
      density_gcm3: "6.15",
      melt: "1193",
      boil: "3737",
      discovered_by: "Carl Gustaf Mosander",
      discovery_year: "1839",
      uses: "Lenti ottiche, acciai speciali e accumulatori idrogeno."
    },
    58: {
      atomic_mass: "140.116",
      phase: "Solido",
      appearance: "Metallo argenteo",
      electron_configuration: "[Xe] 4f1 5d1 6s2",
      electronegativity_pauling: "1.12",
      atomic_radius: "235",
      covalent_radius_pm: "204",
      ionization_energy_kjmol: "534",
      oxidation_states: "+3, +4",
      density_gcm3: "6.77",
      melt: "1068",
      boil: "3716",
      discovered_by: "Martin Heinrich Klaproth",
      discovery_year: "1803",
      uses: "Convertitori catalitici, vetri autoregeneranti e magneti."
    },
    59: {
      atomic_mass: "140.90766",
      phase: "Solido",
      appearance: "Metallo argentato",
      electron_configuration: "[Xe] 4f3 6s2",
      electronegativity_pauling: "1.13",
      atomic_radius: "233",
      covalent_radius_pm: "203",
      ionization_energy_kjmol: "527",
      oxidation_states: "+3, +4",
      density_gcm3: "6.773",
      melt: "1208",
      boil: "3793",
      discovered_by: "Carl Auer von Welsbach",
      discovery_year: "1885",
      uses: "Magneti, leghe per acciai e applicazioni laser."
    },
    60: {
      atomic_mass: "144.242",
      phase: "Solido",
      appearance: "Metallo argentato",
      electron_configuration: "[Xe] 4f4 6s2",
      electronegativity_pauling: "1.14",
      atomic_radius: "229",
      covalent_radius_pm: "201",
      ionization_energy_kjmol: "533",
      oxidation_states: "+3",
      density_gcm3: "7.01",
      melt: "1297",
      boil: "3347",
      discovered_by: "Carl Auer von Welsbach",
      discovery_year: "1885",
      uses: "Magneti permanenti, laser e vetri colorati."
    },
    61: {
      atomic_mass: "145",
      phase: "Solido",
      appearance: "Metallo grigio",
      electron_configuration: "[Xe] 4f5 6s2",
      electronegativity_pauling: "—",
      atomic_radius: "227",
      covalent_radius_pm: "199",
      ionization_energy_kjmol: "540",
      oxidation_states: "+3",
      density_gcm3: "7.26",
      melt: "1315",
      boil: "3273",
      discovered_by: "Jacob A. Marinsky, Lawrence E. Glendenin e Charles D. Coryell",
      discovery_year: "1945",
      uses: "Sorgenti beta per dispositivi portatili e ricerca."
    },
    62: {
      atomic_mass: "150.36",
      phase: "Solido",
      appearance: "Metallo argentato",
      electron_configuration: "[Xe] 4f6 6s2",
      electronegativity_pauling: "1.17",
      atomic_radius: "226",
      covalent_radius_pm: "198",
      ionization_energy_kjmol: "545",
      oxidation_states: "+2, +3",
      density_gcm3: "7.52",
      melt: "1345",
      boil: "2067",
      discovered_by: "Paul-Émile Lecoq de Boisbaudran",
      discovery_year: "1879",
      uses: "Magneti, reattori nucleari e fosfori per schermi."
    },
    63: {
      atomic_mass: "151.964",
      phase: "Solido",
      appearance: "Metallo argentato",
      electron_configuration: "[Xe] 4f7 6s2",
      electronegativity_pauling: "1.20",
      atomic_radius: "226",
      covalent_radius_pm: "198",
      ionization_energy_kjmol: "547",
      oxidation_states: "+2, +3",
      density_gcm3: "5.24",
      melt: "1099",
      boil: "1802",
      discovered_by: "Eugène-Anatole Demarçay",
      discovery_year: "1896",
      uses: "Fosfori per schermi a colori, laser e rivelatori neutronici."
    },
    64: {
      atomic_mass: "157.25",
      phase: "Solido",
      appearance: "Metallo argentato",
      electron_configuration: "[Xe] 4f7 5d1 6s2",
      electronegativity_pauling: "1.20",
      atomic_radius: "233",
      covalent_radius_pm: "196",
      ionization_energy_kjmol: "593",
      oxidation_states: "+3",
      density_gcm3: "7.90",
      melt: "1585",
      boil: "3546",
      discovered_by: "Jean Charles Galissard de Marignac",
      discovery_year: "1880",
      uses: "Magneti permanenti, schermature neutroniche e leghe speciali."
    },
    65: {
      atomic_mass: "158.92535",
      phase: "Solido",
      appearance: "Metallo argentato",
      electron_configuration: "[Xe] 4f9 6s2",
      electronegativity_pauling: "1.21",
      atomic_radius: "232",
      covalent_radius_pm: "194",
      ionization_energy_kjmol: "566",
      oxidation_states: "+3",
      density_gcm3: "8.23",
      melt: "1629",
      boil: "3503",
      discovered_by: "Carl Gustaf Mosander",
      discovery_year: "1843",
      uses: "Fosfori verdi, laser a stato solido e materiali magnetici."
    },
    66: {
      atomic_mass: "162.500",
      phase: "Solido",
      appearance: "Metallo argentato",
      electron_configuration: "[Xe] 4f10 6s2",
      electronegativity_pauling: "1.22",
      atomic_radius: "231",
      covalent_radius_pm: "192",
      ionization_energy_kjmol: "573",
      oxidation_states: "+3",
      density_gcm3: "8.55",
      melt: "1680",
      boil: "2840",
      discovered_by: "Per Teodor Cleve",
      discovery_year: "1886",
      uses: "Laser ad alta potenza, materiali magnetici e illuminazione."
    },
    67: {
      atomic_mass: "164.93033",
      phase: "Solido",
      appearance: "Metallo argentato",
      electron_configuration: "[Xe] 4f11 6s2",
      electronegativity_pauling: "1.23",
      atomic_radius: "230",
      covalent_radius_pm: "192",
      ionization_energy_kjmol: "581",
      oxidation_states: "+3",
      density_gcm3: "8.79",
      melt: "1747",
      boil: "2993",
      discovered_by: "Per Teodor Cleve",
      discovery_year: "1879",
      uses: "Laser medicali, fibre ottiche e rivelatori magnetici."
    },
    68: {
      atomic_mass: "167.259",
      phase: "Solido",
      appearance: "Metallo argentato",
      electron_configuration: "[Xe] 4f12 6s2",
      electronegativity_pauling: "1.24",
      atomic_radius: "229",
      covalent_radius_pm: "189",
      ionization_energy_kjmol: "589",
      oxidation_states: "+3",
      density_gcm3: "9.07",
      melt: "1770",
      boil: "3141",
      discovered_by: "Carl Gustaf Mosander",
      discovery_year: "1843",
      uses: "Laser, fibre ottiche e fosfori verdi per display."
    },
    69: {
      atomic_mass: "168.93422",
      phase: "Solido",
      appearance: "Metallo argentato",
      electron_configuration: "[Xe] 4f13 6s2",
      electronegativity_pauling: "1.25",
      atomic_radius: "228",
      covalent_radius_pm: "190",
      ionization_energy_kjmol: "597",
      oxidation_states: "+3",
      density_gcm3: "9.32",
      melt: "1818",
      boil: "2223",
      discovered_by: "Per Teodor Cleve",
      discovery_year: "1879",
      uses: "Laser medici, fibre ottiche e materiali luminescenti."
    },
    70: {
      atomic_mass: "173.045",
      phase: "Solido",
      appearance: "Metallo argentato",
      electron_configuration: "[Xe] 4f14 6s2",
      electronegativity_pauling: "1.10",
      atomic_radius: "226",
      covalent_radius_pm: "187",
      ionization_energy_kjmol: "603",
      oxidation_states: "+2, +3",
      density_gcm3: "6.90",
      melt: "1097",
      boil: "1469",
      discovered_by: "Jean Charles Galissard de Marignac",
      discovery_year: "1878",
      uses: "Laser infrarossi, leghe e materiali antirottura."
    },
    71: {
      atomic_mass: "174.9668",
      phase: "Solido",
      appearance: "Metallo argentato",
      electron_configuration: "[Xe] 4f14 5d1 6s2",
      electronegativity_pauling: "1.27",
      atomic_radius: "220",
      covalent_radius_pm: "187",
      ionization_energy_kjmol: "523",
      oxidation_states: "+3",
      density_gcm3: "9.84",
      melt: "1936",
      boil: "3675",
      discovered_by: "Georges Urbain",
      discovery_year: "1907",
      uses: "Catalizzatori, ceramiche resistenti e fibre ottiche."
    },
    72: {
      atomic_mass: "178.49",
      phase: "Solido",
      appearance: "Metallo grigio lucente",
      electron_configuration: "[Xe] 4f14 5d2 6s2",
      electronegativity_pauling: "1.30",
      atomic_radius: "212",
      covalent_radius_pm: "175",
      ionization_energy_kjmol: "659",
      oxidation_states: "+4",
      density_gcm3: "13.31",
      melt: "2506",
      boil: "4876",
      discovered_by: "Dirk Coster e George de Hevesy",
      discovery_year: "1923",
      uses: "Leghe resistenti, filamenti e barre per reattori nucleari."
    },
    73: {
      atomic_mass: "180.94788",
      phase: "Solido",
      appearance: "Metallo grigio lucente",
      electron_configuration: "[Xe] 4f14 5d3 6s2",
      electronegativity_pauling: "1.5",
      atomic_radius: "210",
      covalent_radius_pm: "170",
      ionization_energy_kjmol: "761",
      oxidation_states: "+5",
      density_gcm3: "16.65",
      melt: "3290",
      boil: "5731",
      discovered_by: "Anders Gustaf Ekeberg",
      discovery_year: "1802",
      uses: "Superleghe, condensatori e apparecchiature elettroniche."
    },
    74: {
      atomic_mass: "183.84",
      phase: "Solido",
      appearance: "Metallo grigio acciaio",
      electron_configuration: "[Xe] 4f14 5d4 6s2",
      electronegativity_pauling: "2.36",
      atomic_radius: "206",
      covalent_radius_pm: "162",
      ionization_energy_kjmol: "770",
      oxidation_states: "+4, +5, +6",
      density_gcm3: "19.25",
      melt: "3695",
      boil: "5828",
      discovered_by: "Carl Wilhelm Scheele",
      discovery_year: "1781",
      uses: "Filamenti per lampade, acciai rapidi e catalisi."
    },
    75: {
      atomic_mass: "186.207",
      phase: "Solido",
      appearance: "Metallo grigio lucente",
      electron_configuration: "[Xe] 4f14 5d5 6s2",
      electronegativity_pauling: "1.9",
      atomic_radius: "205",
      covalent_radius_pm: "151",
      ionization_energy_kjmol: "760",
      oxidation_states: "+2, +4, +6, +7",
      density_gcm3: "21.02",
      melt: "3459",
      boil: "5869",
      discovered_by: "Ida Noddack, Walter Noddack e Otto Berg",
      discovery_year: "1925",
      uses: "Catalizzatori, filamenti e resistenze ad alta temperatura."
    },
    76: {
      atomic_mass: "190.23",
      phase: "Solido",
      appearance: "Metallo blu-grigio",
      electron_configuration: "[Xe] 4f14 5d6 6s2",
      electronegativity_pauling: "2.2",
      atomic_radius: "203",
      covalent_radius_pm: "144",
      ionization_energy_kjmol: "840",
      oxidation_states: "+2, +3, +4, +6, +8",
      density_gcm3: "22.61",
      melt: "3306",
      boil: "5285",
      discovered_by: "Carl Wilhelm Scheele",
      discovery_year: "1803",
      uses: "Leghe dure, contatti elettrici e catalizzatori chimici."
    },
    77: {
      atomic_mass: "192.217",
      phase: "Solido",
      appearance: "Metallo bianco argenteo",
      electron_configuration: "[Xe] 4f14 5d7 6s2",
      electronegativity_pauling: "2.2",
      atomic_radius: "202",
      covalent_radius_pm: "141",
      ionization_energy_kjmol: "880",
      oxidation_states: "+1, +3, +4, +6",
      density_gcm3: "22.56",
      melt: "2739",
      boil: "4701",
      discovered_by: "Smithson Tennant",
      discovery_year: "1803",
      uses: "Leghe per penne stilografiche, contatti elettrici e catalisi."
    },
    78: {
      atomic_mass: "195.084",
      phase: "Solido",
      appearance: "Metallo bianco lucente",
      electron_configuration: "[Xe] 4f14 5d9 6s1",
      electronegativity_pauling: "2.28",
      atomic_radius: "204",
      covalent_radius_pm: "136",
      ionization_energy_kjmol: "870",
      oxidation_states: "0, +2, +4, +6",
      density_gcm3: "21.45",
      melt: "2041.4",
      boil: "4098",
      discovered_by: "Antonio de Ulloa",
      discovery_year: "1735",
      uses: "Catalizzatori, gioielleria e componenti elettronici."
    },
    79: {
      atomic_mass: "196.966569",
      phase: "Solido",
      appearance: "Metallo giallo lucente",
      electron_configuration: "[Xe] 4f14 5d10 6s1",
      electronegativity_pauling: "2.54",
      atomic_radius: "204",
      covalent_radius_pm: "144",
      ionization_energy_kjmol: "890",
      oxidation_states: "-1, +1, +3",
      density_gcm3: "19.32",
      melt: "1337.33",
      boil: "3129",
      discovered_by: "Preistoria",
      discovery_year: "—",
      uses: "Gioielli, finanza, elettronica e odontoiatria."
    },
    80: {
      atomic_mass: "200.592",
      phase: "Liquido",
      appearance: "Liquido argentato",
      electron_configuration: "[Xe] 4f14 5d10 6s2",
      electronegativity_pauling: "2.00",
      atomic_radius: "204",
      covalent_radius_pm: "149",
      ionization_energy_kjmol: "1007",
      oxidation_states: "+1, +2",
      density_gcm3: "13.534",
      melt: "234.32",
      boil: "629.88",
      discovered_by: "Preistoria",
      discovery_year: "—",
      uses: "Termometri, lampade fluorescenti e amalgami."
    },
    81: {
      atomic_mass: "204.38",
      phase: "Solido",
      appearance: "Metallo grigio-blu",
      electron_configuration: "[Xe] 4f14 5d10 6s2 6p1",
      electronegativity_pauling: "1.62",
      atomic_radius: "196",
      covalent_radius_pm: "148",
      ionization_energy_kjmol: "589",
      oxidation_states: "+1, +3",
      density_gcm3: "11.85",
      melt: "577",
      boil: "1746",
      discovered_by: "William Crookes",
      discovery_year: "1861",
      uses: "Materiali semiconduttori, leghe a bassa fusione e vetri speciali."
    },
    82: {
      atomic_mass: "207.2",
      phase: "Solido",
      appearance: "Metallo grigio-blu",
      electron_configuration: "[Xe] 4f14 5d10 6s2 6p2",
      electronegativity_pauling: "2.33",
      atomic_radius: "180",
      covalent_radius_pm: "146",
      ionization_energy_kjmol: "715",
      oxidation_states: "-4, +2, +4",
      density_gcm3: "11.34",
      melt: "600.61",
      boil: "2022",
      discovered_by: "Preistoria",
      discovery_year: "—",
      uses: "Batterie, schermature radiologiche e leghe saldanti."
    },
    83: {
      atomic_mass: "208.98040",
      phase: "Solido",
      appearance: "Metallo grigio-rosato",
      electron_configuration: "[Xe] 4f14 5d10 6s2 6p3",
      electronegativity_pauling: "2.02",
      atomic_radius: "167",
      covalent_radius_pm: "146",
      ionization_energy_kjmol: "703",
      oxidation_states: "-3, +3, +5",
      density_gcm3: "9.78",
      melt: "544.4",
      boil: "1837",
      discovered_by: "Claude Geoffroy",
      discovery_year: "1753",
      uses: "Leghe a bassa fusione, catalisi e medicina nucleare."
    },
    84: {
      atomic_mass: "209",
      phase: "Solido",
      appearance: "Metallo argenteo",
      electron_configuration: "[Xe] 4f14 5d10 6s2 6p4",
      electronegativity_pauling: "2.0",
      atomic_radius: "167",
      covalent_radius_pm: "146",
      ionization_energy_kjmol: "812",
      oxidation_states: "-2, +2, +4, +6",
      density_gcm3: "9.32",
      melt: "527",
      boil: "1235",
      discovered_by: "Marie e Pierre Curie",
      discovery_year: "1898",
      uses: "Fonti di calore per sonde spaziali e ricerca."
    },
    85: {
      atomic_mass: "210",
      phase: "Solido",
      appearance: "Probabilmente metalloidico scuro",
      electron_configuration: "[Xe] 4f14 5d10 6s2 6p5",
      electronegativity_pauling: "2.2",
      atomic_radius: "—",
      covalent_radius_pm: "145",
      ionization_energy_kjmol: "920",
      oxidation_states: "-1, +1, +3, +5, +7",
      density_gcm3: "7",
      melt: "575",
      boil: "610",
      discovered_by: "Dale R. Corson, Kenneth Ross MacKenzie e Emilio Segrè",
      discovery_year: "1940",
      uses: "Traccianti radioattivi e ricerca scientifica."
    },
    86: {
      atomic_mass: "222",
      phase: "Gas",
      appearance: "Gas radioattivo incolore",
      electron_configuration: "[Xe] 4f14 5d10 6s2 6p6",
      electronegativity_pauling: "—",
      atomic_radius: "120",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "1037",
      oxidation_states: "0, +2",
      density_gcm3: "0.00973",
      melt: "202",
      boil: "211.5",
      discovered_by: "Friedrich Ernst Dorn",
      discovery_year: "1900",
      uses: "Tracciamento geologico, radioterapia e monitoraggio radon."
    },
    87: {
      atomic_mass: "223",
      phase: "Solido",
      appearance: "Metallo argenteo altamente radioattivo",
      electron_configuration: "[Rn] 7s1",
      electronegativity_pauling: "0.7",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "380",
      oxidation_states: "+1",
      density_gcm3: "1.87",
      melt: "300",
      boil: "950",
      discovered_by: "Marguerite Perey",
      discovery_year: "1939",
      uses: "Ricerca scientifica e produzione di altri isotopi."
    },
    88: {
      atomic_mass: "226",
      phase: "Solido",
      appearance: "Metallo argenteo radioattivo",
      electron_configuration: "[Rn] 7s2",
      electronegativity_pauling: "0.9",
      atomic_radius: "215",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "509",
      oxidation_states: "+2",
      density_gcm3: "5.5",
      melt: "973",
      boil: "2010",
      discovered_by: "Marie e Pierre Curie",
      discovery_year: "1898",
      uses: "Radioterapia, sorgenti di neutroni e ricerca."
    },
    89: {
      atomic_mass: "227",
      phase: "Solido",
      appearance: "Metallo argenteo",
      electron_configuration: "[Rn] 6d1 7s2",
      electronegativity_pauling: "1.1",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "499",
      oxidation_states: "+3",
      density_gcm3: "10",
      melt: "1324",
      boil: "3471",
      discovered_by: "André-Louis Debierne",
      discovery_year: "1899",
      uses: "Ricerca nucleare e sorgenti di neutroni."
    },
    90: {
      atomic_mass: "232.0377",
      phase: "Solido",
      appearance: "Metallo grigio argenteo",
      electron_configuration: "[Rn] 6d2 7s2",
      electronegativity_pauling: "1.3",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "587",
      oxidation_states: "+4",
      density_gcm3: "11.7",
      melt: "2023",
      boil: "5093",
      discovered_by: "Jöns Jacob Berzelius",
      discovery_year: "1828",
      uses: "Combustibile nucleare, leghe resistenti e sorgenti di calore."
    },
    91: {
      atomic_mass: "231.03588",
      phase: "Solido",
      appearance: "Metallo grigio argentato",
      electron_configuration: "[Rn] 5f2 6d1 7s2",
      electronegativity_pauling: "1.5",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "568",
      oxidation_states: "+4, +5",
      density_gcm3: "15.37",
      melt: "1841",
      boil: "4300",
      discovered_by: "Friedrich Oskar Giesel",
      discovery_year: "1901",
      uses: "Ricerca nucleare e studi su attinidi."
    },
    92: {
      atomic_mass: "238.02891",
      phase: "Solido",
      appearance: "Metallo grigio argenteo",
      electron_configuration: "[Rn] 5f3 6d1 7s2",
      electronegativity_pauling: "1.38",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "598",
      oxidation_states: "+3, +4, +5, +6",
      density_gcm3: "18.95",
      melt: "1408",
      boil: "4404",
      discovered_by: "Martin Heinrich Klaproth",
      discovery_year: "1789",
      uses: "Energia nucleare, armamenti e radiografia industriale."
    },
    93: {
      atomic_mass: "237",
      phase: "Solido",
      appearance: "Metallo argenteo",
      electron_configuration: "[Rn] 5f4 6d1 7s2",
      electronegativity_pauling: "1.36",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "604",
      oxidation_states: "+3, +4, +5, +6",
      density_gcm3: "20.45",
      melt: "917",
      boil: "4175",
      discovered_by: "Edwin McMillan e Philip H. Abelson",
      discovery_year: "1940",
      uses: "Generatori nucleari e ricerca scientifica."
    },
    94: {
      atomic_mass: "244",
      phase: "Solido",
      appearance: "Metallo argentato",
      electron_configuration: "[Rn] 5f6 7s2",
      electronegativity_pauling: "1.28",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "585",
      oxidation_states: "+3, +4, +5, +6",
      density_gcm3: "19.8",
      melt: "912.5",
      boil: "3501",
      discovered_by: "Glenn T. Seaborg, Arthur Wahl e Joseph Kennedy",
      discovery_year: "1940",
      uses: "Armi nucleari, generatori termoelettrici e ricerca."
    },
    95: {
      atomic_mass: "243",
      phase: "Solido",
      appearance: "Metallo argenteo",
      electron_configuration: "[Rn] 5f7 7s2",
      electronegativity_pauling: "1.3",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "578",
      oxidation_states: "+2, +3, +4, +5, +6",
      density_gcm3: "13.67",
      melt: "1449",
      boil: "2880",
      discovered_by: "Glenn T. Seaborg e collaboratori",
      discovery_year: "1944",
      uses: "Sorgenti di neutroni, produzione di elementi più pesanti e ricerca."
    },
    96: {
      atomic_mass: "247",
      phase: "Solido",
      appearance: "Metallo argenteo",
      electron_configuration: "[Rn] 5f7 6d1 7s2",
      electronegativity_pauling: "1.28",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "581",
      oxidation_states: "+3, +4",
      density_gcm3: "13.51",
      melt: "1613",
      boil: "3383",
      discovered_by: "Glenn T. Seaborg e collaboratori",
      discovery_year: "1944",
      uses: "Sorgenti di neutroni e ricerca nucleare."
    },
    97: {
      atomic_mass: "247",
      phase: "Solido",
      appearance: "Metallo argenteo",
      electron_configuration: "[Rn] 5f9 7s2",
      electronegativity_pauling: "1.3",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "601",
      oxidation_states: "+3, +4",
      density_gcm3: "14",
      melt: "1259",
      boil: "2900",
      discovered_by: "Glenn T. Seaborg e collaboratori",
      discovery_year: "1949",
      uses: "Ricerca nucleare e produzione di isotopi."
    },
    98: {
      atomic_mass: "251",
      phase: "Solido",
      appearance: "Metallo argenteo",
      electron_configuration: "[Rn] 5f10 7s2",
      electronegativity_pauling: "1.3",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "608",
      oxidation_states: "+2, +3, +4",
      density_gcm3: "15.1",
      melt: "1173",
      boil: "1743",
      discovered_by: "Glenn T. Seaborg e collaboratori",
      discovery_year: "1950",
      uses: "Ricerca, medicina nucleare sperimentale e produzione di elementi transuranici."
    },
    99: {
      atomic_mass: "252",
      phase: "Solido",
      appearance: "Metallo argenteo",
      electron_configuration: "[Rn] 5f11 7s2",
      electronegativity_pauling: "1.3",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "619",
      oxidation_states: "+3",
      density_gcm3: "8.84",
      melt: "1130",
      boil: "1269",
      discovered_by: "Albert Ghiorso e collaboratori",
      discovery_year: "1952",
      uses: "Ricerca nucleare e applicazioni mediche sperimentali."
    },
    100: {
      atomic_mass: "257",
      phase: "Solido",
      appearance: "Metallo argenteo",
      electron_configuration: "[Rn] 5f12 7s2",
      electronegativity_pauling: "1.3",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "627",
      oxidation_states: "+2, +3",
      density_gcm3: "9.7",
      melt: "1800",
      boil: "—",
      discovered_by: "Albert Ghiorso e collaboratori",
      discovery_year: "1952",
      uses: "Ricerca sulla sintesi di elementi superpesanti."
    },
    101: {
      atomic_mass: "258",
      phase: "Solido",
      appearance: "Metallo argenteo",
      electron_configuration: "[Rn] 5f13 7s2",
      electronegativity_pauling: "1.3",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "635",
      oxidation_states: "+2, +3",
      density_gcm3: "—",
      melt: "1100",
      boil: "—",
      discovered_by: "Albert Ghiorso e collaboratori",
      discovery_year: "1955",
      uses: "Ricerca scientifica su elementi transuranici."
    },
    102: {
      atomic_mass: "259",
      phase: "Solido",
      appearance: "Metallo argenteo",
      electron_configuration: "[Rn] 5f14 7s2",
      electronegativity_pauling: "1.3",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "642",
      oxidation_states: "+2, +3",
      density_gcm3: "9.9",
      melt: "1100",
      boil: "—",
      discovered_by: "Albert Ghiorso e collaboratori",
      discovery_year: "1957",
      uses: "Ricerca nucleare e sintesi di nuovi elementi."
    },
    103: {
      atomic_mass: "262",
      phase: "Solido",
      appearance: "Metallo argenteo",
      electron_configuration: "[Rn] 5f14 6d1 7s2",
      electronegativity_pauling: "1.3",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "—",
      oxidation_states: "+3",
      density_gcm3: "—",
      melt: "1900",
      boil: "—",
      discovered_by: "Albert Ghiorso e collaboratori",
      discovery_year: "1961",
      uses: "Ricerca sulla chimica degli attinidi."
    },
    104: {
      atomic_mass: "267",
      phase: "Solido",
      appearance: "Sintetico",
      electron_configuration: "[Rn] 5f14 6d2 7s2",
      electronegativity_pauling: "—",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "—",
      oxidation_states: "+4",
      density_gcm3: "—",
      melt: "2400",
      boil: "—",
      discovered_by: "Georgy Flerov e collaboratori",
      discovery_year: "1964",
      uses: "Ricerca scientifica."
    },
    105: {
      atomic_mass: "268",
      phase: "Solido",
      appearance: "Sintetico",
      electron_configuration: "[Rn] 5f14 6d3 7s2",
      electronegativity_pauling: "—",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "—",
      oxidation_states: "+5",
      density_gcm3: "—",
      melt: "—",
      boil: "—",
      discovered_by: "Dmitri Cheltsov e collaboratori",
      discovery_year: "1967",
      uses: "Ricerca scientifica."
    },
    106: {
      atomic_mass: "269",
      phase: "Solido",
      appearance: "Sintetico",
      electron_configuration: "[Rn] 5f14 6d4 7s2",
      electronegativity_pauling: "—",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "—",
      oxidation_states: "+6",
      density_gcm3: "—",
      melt: "—",
      boil: "—",
      discovered_by: "Albert Ghiorso e collaboratori",
      discovery_year: "1974",
      uses: "Ricerca scientifica."
    },
    107: {
      atomic_mass: "270",
      phase: "Solido",
      appearance: "Sintetico",
      electron_configuration: "[Rn] 5f14 6d5 7s2",
      electronegativity_pauling: "—",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "—",
      oxidation_states: "+7",
      density_gcm3: "—",
      melt: "—",
      boil: "—",
      discovered_by: "Peter Armbruster e Gottfried Münzenberg",
      discovery_year: "1981",
      uses: "Ricerca scientifica."
    },
    108: {
      atomic_mass: "270",
      phase: "Solido",
      appearance: "Sintetico",
      electron_configuration: "[Rn] 5f14 6d6 7s2",
      electronegativity_pauling: "—",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "—",
      oxidation_states: "+8",
      density_gcm3: "—",
      melt: "—",
      boil: "—",
      discovered_by: "Peter Armbruster e Gottfried Münzenberg",
      discovery_year: "1984",
      uses: "Ricerca scientifica."
    },
    109: {
      atomic_mass: "278",
      phase: "Solido",
      appearance: "Sintetico",
      electron_configuration: "[Rn] 5f14 6d7 7s2",
      electronegativity_pauling: "—",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "—",
      oxidation_states: "+1, +3",
      density_gcm3: "—",
      melt: "—",
      boil: "—",
      discovered_by: "Peter Armbruster e Gottfried Münzenberg",
      discovery_year: "1982",
      uses: "Ricerca scientifica."
    },
    110: {
      atomic_mass: "281",
      phase: "Solido",
      appearance: "Sintetico",
      electron_configuration: "[Rn] 5f14 6d9 7s1",
      electronegativity_pauling: "—",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "—",
      oxidation_states: "+2, +4",
      density_gcm3: "—",
      melt: "—",
      boil: "—",
      discovered_by: "Peter Armbruster e Gottfried Münzenberg",
      discovery_year: "1994",
      uses: "Ricerca scientifica."
    },
    111: {
      atomic_mass: "282",
      phase: "Solido",
      appearance: "Sintetico",
      electron_configuration: "[Rn] 5f14 6d10 7s1",
      electronegativity_pauling: "—",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "—",
      oxidation_states: "+1, +3",
      density_gcm3: "—",
      melt: "—",
      boil: "—",
      discovered_by: "Peter Armbruster e Gottfried Münzenberg",
      discovery_year: "1994",
      uses: "Ricerca scientifica."
    },
    112: {
      atomic_mass: "285",
      phase: "Solido",
      appearance: "Sintetico",
      electron_configuration: "[Rn] 5f14 6d10 7s2",
      electronegativity_pauling: "—",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "—",
      oxidation_states: "+2",
      density_gcm3: "14",
      melt: "357",
      boil: "84",
      discovered_by: "Sigurd Hofmann e collaboratori",
      discovery_year: "1996",
      uses: "Ricerca scientifica."
    },
    113: {
      atomic_mass: "286",
      phase: "Solido",
      appearance: "Sintetico",
      electron_configuration: "[Rn] 5f14 6d10 7s2 7p1",
      electronegativity_pauling: "—",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "—",
      oxidation_states: "+1, +3",
      density_gcm3: "—",
      melt: "—",
      boil: "—",
      discovered_by: "Riken (Giappone)",
      discovery_year: "2004",
      uses: "Ricerca scientifica."
    },
    114: {
      atomic_mass: "289",
      phase: "Solido",
      appearance: "Sintetico",
      electron_configuration: "[Rn] 5f14 6d10 7s2 7p2",
      electronegativity_pauling: "—",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "—",
      oxidation_states: "+2, +4",
      density_gcm3: "—",
      melt: "—",
      boil: "—",
      discovered_by: "Joint Institute for Nuclear Research",
      discovery_year: "1998",
      uses: "Ricerca scientifica."
    },
    115: {
      atomic_mass: "290",
      phase: "Solido",
      appearance: "Sintetico",
      electron_configuration: "[Rn] 5f14 6d10 7s2 7p3",
      electronegativity_pauling: "—",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "—",
      oxidation_states: "+1, +3",
      density_gcm3: "—",
      melt: "—",
      boil: "—",
      discovered_by: "Joint Institute for Nuclear Research",
      discovery_year: "2003",
      uses: "Ricerca scientifica."
    },
    116: {
      atomic_mass: "293",
      phase: "Solido",
      appearance: "Sintetico",
      electron_configuration: "[Rn] 5f14 6d10 7s2 7p4",
      electronegativity_pauling: "—",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "—",
      oxidation_states: "+2, +4",
      density_gcm3: "—",
      melt: "—",
      boil: "—",
      discovered_by: "Joint Institute for Nuclear Research",
      discovery_year: "2000",
      uses: "Ricerca scientifica."
    },
    117: {
      atomic_mass: "294",
      phase: "Solido",
      appearance: "Sintetico",
      electron_configuration: "[Rn] 5f14 6d10 7s2 7p5",
      electronegativity_pauling: "—",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "—",
      oxidation_states: "-1, +1, +3, +5",
      density_gcm3: "—",
      melt: "—",
      boil: "—",
      discovered_by: "Joint Institute for Nuclear Research",
      discovery_year: "2010",
      uses: "Ricerca scientifica."
    },
    118: {
      atomic_mass: "294",
      phase: "Gas",
      appearance: "Sintetico, presumibilmente gas nobile",
      electron_configuration: "[Rn] 5f14 6d10 7s2 7p6",
      electronegativity_pauling: "—",
      atomic_radius: "—",
      covalent_radius_pm: "—",
      ionization_energy_kjmol: "—",
      oxidation_states: "0, +2",
      density_gcm3: "—",
      melt: "—",
      boil: "—",
      discovered_by: "Joint Institute for Nuclear Research",
      discovery_year: "2006",
      uses: "Ricerca scientifica."
    }
  };
  global.STATIC_ELEMENT_PROPS = DATA;
  global.seedElementProps = function(elements){
    if(!Array.isArray(elements)) return;
    elements.forEach(function(el){
      if(!el || typeof el !== 'object') return;
      const base = DATA[el.Z];
      if(base){
        el.props = Object.assign({}, base);
      }
    });
  };
})(typeof window !== 'undefined' ? window : globalThis);
